### ISSUE TITLE
Crashing when placing crafting table

### ISSUE THREAD

**Issue by jjdarrel** [Naxanria/Harvest#1]
I downloaded the latest version 1.16.2-1.0.2, I have 36 other mods installed, not sure if they are incompatible but once I removed "harvest" I was able to place the crafting table down. I haven't tried to re-install it. I'm on forge 33.0.22

**Comment by Naxanria** [comment]
Do you have the crashlog? Without it I cant really check :)

**Comment by jjdarrel** [comment]
[crash-2020-09-10_08.39.07-client.txt](https://github.com/Naxanria/Harvest/files/5201661/crash-2020-09-10_08.39.07-client.txt)

Sorry about that, I assumed I had uploaded it. Created a new crash log about now with no mods other than forge installed. 

I notice it happens whenever I right click grass. Not necessarily placing down crafting table.

**Comment by Naxanria** [comment]
I cant replicate the issue, at least with forge 33.0.57. So I hope it will be fixed for you with this.

**Comment by jjdarrel** [comment]
Using your 1.0.2 file, I still had the same crash even when using forge 33.0.57 and 33.0.61 but when I used your updated 1.0.3 harvest file, it all seemed to work flawlessly. Thanks
