### ISSUE TITLE
Incompatibility with Thermal Cultivation

### ISSUE THREAD

**Issue by Hekera** [Naxanria/Harvest#3]
On MC 1.16.5 with Harvest 1.16.3-1.0.3 and Thermal mods 1.3, right clicking to harvest 2-block tall plants such as flax and corn does not work properly. See screenshot for more details. 
![image](https://user-images.githubusercontent.com/40907168/143322553-fe41a93d-87e5-4eb2-99a9-c84e9a0c3262.png)

**Comment by Naxanria** [comment]
You can blacklist them, that would fix the issue
